id: 1
name: amorce
environments:
  production:
    build:
      commands:
        - 'npm ci'
        - 'npm run build'
        - 'php artisan config:cache'
        - 'php artisan route:cache'
    deploy:
      - 'php artisan migrate --force'
      - 'php artisan db:seed --force'
      - './deploy.sh'
    workers:
      - command: 'php artisan queue:work --tries=3 --timeout=600'
        quantity: 1
    web:
      timeout: 120
